version: '3.1'

services:
  app:
    image: "verdaccio/verdaccio:4"
    container_name: "verdaccio"
    environment:
      - VERDACCIO_PORT
    ports:
      - "$VERDACCIO_PORT:$VERDACCIO_PORT"
    volumes:
      - "./verdaccio:/verdaccio"
